### ISSUE TITLE
Allow flash-all to be disabled/enabled by tapping BUTTON C

### ISSUE THREAD

**Issue by mitchhentges** [stevelyall/NotGetHitByBus#1]
- [x] On program start, lights are flashing
- [x] If lights are flashing and BUTTON C is pressed, buttons stop flashing
- [x] If lights aren't flashing and BUTTON C is pressed, buttons start flashing

**Comment by stevelyall** [comment]
By buttons flashing I'm guessing we mean lights? 
If so looks like we've got the first item covered.

**Comment by mitchhentges** [comment]
Yeah, English is hard

**Comment by mitchhentges** [comment]
I'll leave some debug in the scripts for later use, as it will definitely help

**Comment by stevelyall** [comment]
Legendary! Do the button presses work that way, or do we need to do something to debounce the switches?

**Comment by mitchhentges** [comment]
The button presses work as-is :)

**Comment by stevelyall** [comment]
Holy shit, that will save us a ton of work!

**Comment by mitchhentges** [comment]
![You're goddamn right](https://cloud.githubusercontent.com/assets/7784737/5004883/b117c2ec-69d8-11e4-82b0-e59a60f55813.gif)

**Comment by stevelyall** [comment]
I'm still impressed you got it working without us running into any issues with the switches.

Page 13 in the user guide (http://ww1.microchip.com/downloads/en/DeviceDoc/61159B.pdf BTW) says:
"The switches do not have any debounce circuitry and require the use of internal pull- up resistors; this allows you to investigate debounce techniques."

Maybe we have a different revision of the board with nicer switches, might run into issues later, or Microchip just isn't as pro? Maybe the delay imposed by the timer is enough that it doesn't matter, and we just get lucky?

**Comment by mitchhentges** [comment]
Perhaps part of the top configuration has to do with these pull-up things
