### ISSUE TITLE
Crosswalk mode

### ISSUE THREAD

**Issue by stevelyall** [stevelyall/NotGetHitByBus#3]
- [x] Green light
- [x] pressing button B changes lights to red (yellow first)
- [x] returns to green after a delay

**Comment by mitchhentges** [comment]
This one's probably going to be the most tough. If you want to meet up for strategizing on Saturday, I've got some ideas about how to use only the one interrupt system.

**Comment by stevelyall** [comment]
I had wondered about that, was going to ask if you had any ideas. Worth
discussing.

**Comment by stevelyall** [comment]
"It's going to be the most tough" no you lied
