### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by mitchhentges** [stevelyall/NotGetHitByBus#4]
- [x] Regardless of what state the system is in, pressing BUTTON A will turn off all lights except green
  - [x] Hitting BUTTON A will enable reset mode
  - [x] Hitting BUTTON C will enable testing mode

**Comment by stevelyall** [comment]
MFW finished

**Comment by stevelyall** [comment]
Mitch, you need to learn to close issues u fatty swagmaster
