### ISSUE TITLE
Put everything together

### ISSUE THREAD

**Issue by mitchhentges** [stevelyall/NotGetHitByBus#5]
By the time we reach milestone 3, everything will probably be in a little bit of a mess. #cleanupTime

From Haytham:
- [x] conversion for ms, documentation for exact timer
- [x] documizzle shizzle
- [x] test cases

**Comment by stevelyall** [comment]
Looks like we're good to go. I added a bit to our documentation and de-plagarized some comments in the code. After the merge I'm having a hard time building the project thanks to awesome MPLAB, so maybe we should double-checkify that it isn't broken before we hand in. It's probably still good but you never know.

**Comment by mitchhentges** [comment]
The most recent master is definitely good, I just compiled on that machine in the CANLAB before I left

**Comment by stevelyall** [comment]
yeah I figured, my only changes were comments. I'll have to mess with it again to get it working on my laptop

**Comment by mitchhentges** [comment]
Eyyyyy we pulled it off - 2 months later :wink:

**Comment by stevelyall** [comment]
Thank goodness I closed the issue!
