### ISSUE TITLE
flashing mode push green button

### ISSUE THREAD

**Issue by stevelyall** [stevelyall/NotGetHitByBus#7]
When the lights are flashing, pushing the button for green light mode will turn all lights off, pushing green again starts green mode. 

The opposite is also true, I fixed a "feature" which caused the green light to be off when the yellow and red lights were toggled on, but now two pushes are required to change to flashing mode from green mode.

Do we care that a second push is required to change modes after clearing modes?

**Comment by mitchhentges** [comment]
I would say... yes? Let's check it out soon

**Comment by stevelyall** [comment]
Yeah, I'm busy learning about databases in C#. Geez.

**Comment by mitchhentges** [comment]
Goddamn C#

**Comment by mitchhentges** [comment]
Being

**Comment by mitchhentges** [comment]
Sharp

**Comment by stevelyall** [comment]
Better than being flat?

**Comment by mitchhentges** [comment]
![shapez](https://cloud.githubusercontent.com/assets/7784737/5054338/557e0068-6c08-11e4-85af-02c6cc317594.png)

**Comment by stevelyall** [comment]
is that polymorphism?
